Fix cmon service to make it work better w/ chef 0.10.10
The script shabang needs to be at the top of the script

diff --git a/cmon/files/default/etc/init.d/cmon b/cmon/files/default/etc/init.d/cmon
--- a/cmon/files/default/etc/init.d/cmon
+++ b/cmon/files/default/etc/init.d/cmon
@@ -1,7 +1,8 @@
+#!/bin/bash
 # All files in this package is subject to the GPL v2 license
 # More information is in the COPYING file in the top directory of this package.
 # Copyright (C) 2011 severalnines.com
-#!/bin/bash
+
 # chkconfig: 235 99 20
 # description: cmon start/stop script
 
@@ -14,122 +15,142 @@
 # Short-Description:    cmon - cluster monitor
 ### END INIT INFO
 
-SBINDIR=/usr/local/cmon/sbin/
-RUNNING_DIR=/var/run/
+SBINDIR=/usr/local/cmon/sbin
+RUNNING_DIR=/var/run
 PIDFILE=${RUNNING_DIR}/cmon.pid
 
 LOCKFILE=""
-if [ -d /var/lock/subsys ]; then
+if [ -d /var/lock/subsys ]
+then
   LOCKFILE=/var/lock/subsys/cmon
 else
   LOCKFILE=/var/lock/cmon
 fi
 
 OPTIONS="--config-file=/etc/cmon.cnf"
-PROGNAME="cmon"
+PROGNAME=cmon
 STARTCMON="$SBINDIR/$PROGNAME $OPTIONS"
 
 RETVAL=0
+
 pidof_prog() {
-        if [ -e "$PIDFILE" ]; then
-                if pidof $PROGNAME | tr ' ' '\n' | grep $(cat $PIDFILE); then
-                    return 0
-                fi
-        fi
-        return 1
+  if [ -e "$PIDFILE" ]
+  then
+    if pidof $PROGNAME | tr ' ' '\n' | grep $(cat $PIDFILE)
+    then
+      return 0
+    fi
+  fi
+  return 1
 }
+
 start() {
-  	echo -n "Starting $PROGNAME $OPTIONS :"
-        PID=`pgrep $PROGNAME`
-        if [ -n "$PID" ]; then
-            printf "$PROGNAME is already running with pid $PID"
-            return 0
-        else
-	    if [ ! -f $SBINDIR/$PROGNAME ]; then
-	          echo -n "$PROGNAME executable not found in $SBINDIR"
-		      fi
-            $STARTCMON  > /dev/null 2>&1 &
-            echo $! > $PIDFILE	            
-	            touch $LOCKFILE
-            sleep 1
-            PID=`cat $PIDFILE`
-            if [ "$PID" ]; then
-	                echo " ok"
-                return 1
-            else
-	                echo " failed"
-                return 0
-            fi
-       fi
+  echo -n "Starting $PROGNAME $OPTIONS :"
+  PID=`pgrep -f "$STARTCMON"`
+  if [ -n "$PID" ]
+  then
+    printf "$PROGNAME is already running with pid $PID\n"
+    return 0
+  else
+    if [ ! -f $SBINDIR/$PROGNAME ]
+    then
+      echo -n "$PROGNAME executable not found in $SBINDIR\n"
+    fi
+    $STARTCMON  > /dev/null 2>&1 &
+    echo $! > $PIDFILE              
+    touch $LOCKFILE
+    sleep 1
+    PID=`cat $PIDFILE`
+    if [ "$PID" ]
+    then
+      echo " ok"
+      return 0
+    else
+      echo " failed"
+      return 1
+    fi
+  fi
 }
+
 stop() {
-       echo -n "Stopping $PROGNAME : "
-        PID=`pgrep $PROGNAME`
-        if [ -n "$PID" ]; then
-           kill -15 $PID
-        else
-          `rm -f ${PIDFILE}`
-          `rm -f ${LOCKFILE}`
-           echo " failed"
- 	         return 0
-        fi
-        i=1
-        while [ "`pgrep $PROGNAME`" ];
-        do
-           if [ $i -eq 60 ]; then
-             echo "giving up after 60 secods"
-             return 0
-           fi
-           i=`expr $i + 1`
-           sleep 1
-        done
-	PID=`pgrep $PROGNAME`
-	if [ -n "$PID" ]; then
-           echo " failed"
-           return 0
-        else
-          `rm -f ${PIDFILE}`
-          `rm -f ${LOCKFILE}`
-          echo " ok"
-          return 1
-        fi
+  echo -n "Stopping $PROGNAME : "
+  PID=`pgrep -f "$STARTCMON"`
+  if [ -n "$PID" ]
+  then
+    kill -15 $PID
+    return 0
+  else
+    `rm -f ${PIDFILE}`
+    `rm -f ${LOCKFILE}`
+    echo " failed"
+    # should really be 1 but chef complains
+    return 0
+  fi
+
+  i=1
+  while [ "`pgrep -f "$STARTCMON"`" ]
+  do
+    if [ $i -eq 60 ]; then
+      echo "giving up after 60 secods"
+      return 0
+    fi
+    i=`expr $i + 1`
+    sleep 1
+  done
+  
+  PID=`pgrep -f "$STARTCMON"`
+  if [ -n "$PID" ]
+  then
+    echo " failed"
+    # should really be 1 but chef complains
+    return 0
+  else
+    `rm -f ${PIDFILE}`
+    `rm -f ${LOCKFILE}`
+    echo " ok"
+    return 0
+  fi
 }
+
 case "$1" in
   init|initial)
-        initial
-        ;;
+    initial
+    ;;
   start)
-        start
-        RETVAL=$?
-        ;;
+    start
+    RETVAL=$?
+    ;;
   stop)
-        stop
-        RETVAL=$?
-        ;;
+    stop
+    RETVAL=$?
+    ;;
   status)
-        PID=$(pidof_prog) || true
-        if [ -n "$PID" ]; then
-             echo "$PROGNAME is running (pid $PID)."
-        else
-             echo "$PROGNAME is NOT running."
-        fi
-        RETVAL=$?
-        ;;
-  condrestart|try-restart)	
-        PID=$(pidof_prog) || true
-	if [ -n "$PID" ]; then
-         stop		     
-	 start
-	fi
-	;;
+    PID=$(pidof_prog) || true
+    if [ -n "$PID" ]
+    then
+      echo "$PROGNAME is running (pid $PID)."
+      RETVAL=0
+    else
+      echo "$PROGNAME is NOT running."
+      RETVAL=1
+    fi
+    ;;
+  condrestart|try-restart) 
+    PID=$(pidof_prog) || true
+    if [ -n "$PID" ]
+    then
+      stop         
+     start
+    fi
+    ;;
   restart|reload|force-reload)
-        stop
-        start
-        RETVAL=$?
-        ;;
+    stop
+    start
+    RETVAL=$?
+    ;;
   *)
-        echo $"Usage: $0 {start|stop|restart|status}"
-
-        exit 1
+    echo $"Usage: $0 {start|stop|restart|status}"
+    exit 1
 esac
-exit $?
+
+exit $RETVAL
