Cleanup mysqld init.d script and shabang at the top

diff --git a/galera/templates/default/mysqld.erb b/galera/templates/default/mysqld.erb
--- a/galera/templates/default/mysqld.erb
+++ b/galera/templates/default/mysqld.erb
@@ -1,8 +1,9 @@
+
+#!/bin/bash
 # All files in this package is subject to the GPL v2 license
 # More information is in the COPYING file in the top directory of this package.
 # Copyright (C) 2011 severalnines.com
 
-#!/bin/bash
 # chkconfig: 235 99 20
 # description: mysqld start/stop script
 
@@ -32,112 +33,129 @@ RETVAL=0
 . /lib/lsb/init-functions
 
 pidof_prog() {
-        if [ -e "$PIDFILE" ]; then
-                if pidof $PROGNAME | tr ' ' '\n' | grep $(cat $PIDFILE); then
-                        return 0
-                fi
-        fi
-        return 1
+  if [ -e "$PIDFILE" ]
+  then
+    if pidof $PROGNAME | tr ' ' '\n' | grep $(cat $PIDFILE)
+    then
+      return 0
+    fi
+  fi
+  return 1
 }
+
 start() {
-  	echo -n "Starting $PROGNAME : "
-        PID=`pgrep $PROGNAME`
-        if [ -n "$PID" ]; then
-            printf "$PROGNAME is already running with pid $PID 
-"
-            return 0
-        else
-	    if [ ! -f $SBINDIR/$PROGNAME ]; then
-	      echo -n "$PROGNAME executable not found in $SBINDIR"
-	    fi
-            $STARTNDBD  > /dev/null 2>&1 &
-            sleep 1
-            PID=`pgrep -o $PROGNAME`
-            if [ -n "$PID" ]; then
-              echo $PID > $PIDFILE
-            fi
-	        touch $LOCKFILE
-	        chmod 777 $PIDFILE
-            sleep 1
-            PID=`cat $PIDFILE`
-            if [ "$PID" ]; then
-	            echo "ok"
-	            `ln -s /var/run/mysqld/mysqld.sock  /tmp/mysql.sock > /dev/null 2>&1`
-                return 1
-            else
-	            echo "failed"
-                return 0
-            fi
-       fi
+  echo -n "Starting $PROGNAME : "
+  PID=`pgrep $PROGNAME`
+  if [ -n "$PID" ]
+  then
+    printf "$PROGNAME is already running with pid $PID\n"
+    return 0
+  else
+    if [ ! -f $SBINDIR/$PROGNAME ]
+    then
+      echo -n "$PROGNAME executable not found in $SBINDIR"
+    fi
+    
+    $STARTNDBD  > /dev/null 2>&1 &
+    sleep 1
+    PID=`pgrep -o $PROGNAME`
+    if [ -n "$PID" ]
+    then
+      echo $PID > $PIDFILE
+    fi
+    touch $LOCKFILE
+    chmod 777 $PIDFILE
+    sleep 1
+    PID=`cat $PIDFILE`
+    if [ "$PID" ]
+    then
+      echo "ok"
+      `ln -s /var/run/mysqld/mysqld.sock  /tmp/mysql.sock > /dev/null 2>&1`
+      return 1
+    else
+      echo "failed"
+      return 0
+    fi
+  fi
 }
+
 stop() {
-       echo -n "Stopping $PROGNAME : "
-        PID=`pgrep $PROGNAME`
-        if [ -n "$PID" ]; then
-           kill -15 $PID
-        else
-          `rm -f ${PIDFILE}`
-          `rm -f ${LOCKFILE}`
-           echo "not started"
- 	      return 0
-        fi
-        i=1
-        while [ "`pgrep $PROGNAME`" ];
-        do
-           if [ $i -eq 60 ]; then
-             echo "giving up after 60 secods"
-             return 0
-           fi
-           i=`expr $i + 1`
-           sleep 1
-        done
-	PID=`pgrep $PROGNAME`
-	if [ -n "$PID" ]; then
-           echo " failed"
-           return 0
-        else
-          `rm -f ${PIDFILE}`
-          `rm -f ${LOCKFILE}`
-          echo "ok"
-          return 1
-        fi
+  echo -n "Stopping $PROGNAME : "
+  PID=`pgrep $PROGNAME`
+  if [ -n "$PID" ]
+  then
+    kill -15 $PID
+  else
+    `rm -f ${PIDFILE}`
+    `rm -f ${LOCKFILE}`
+    echo "not started"
+    return 0
+  fi
+  
+  i=1
+  while [ "`pgrep $PROGNAME`" ];
+  do
+    if [ $i -eq 60 ]
+    then
+      echo "giving up after 60 secods"
+      return 0
+    fi
+    i=`expr $i + 1`
+    sleep 1
+  done
+	
+  PID=`pgrep $PROGNAME`
+	if [ -n "$PID" ] 
+  then
+    echo " failed"
+    return 0
+  else
+    `rm -f ${PIDFILE}`
+    `rm -f ${LOCKFILE}`
+    echo "ok"
+    return 1
+  fi
 }
+
 case "$1" in
   init|initial)
-      initial
-      ;;
+    initial
+    ;;
   start)
-      start
-      RETVAL=$?
-      ;;
+    start
+    RETVAL=$?
+    ;;
   stop)
-      stop
-      RETVAL=$?
-      ;;
+    stop
+    RETVAL=$?
+    ;;
   status)
-      PID=$(pidof_prog) || true
-      if [ -n "$PID" ]; then
-           echo "already running (pid $PID)."
-      else
-           echo "\is NOT running."
-      fi
-      RETVAL=$?
-      ;;
-   condrestart|try-restart)	
-      PID=$(pidof_prog) || true
-      if [ -n "$PID" ]; then
-          stop
+    PID=$(pidof_prog) || true
+    if [ -n "$PID" ] 
+    then
+      echo "$PROGNAME already running (pid $PID)."
+      RETVAL=0
+    else
+      echo "PROGNAME is NOT running."
+      RETVAL=1
+    fi
+    ;;
+  condrestart|try-restart)	
+    PID=$(pidof_prog) || true
+    if [ -n "$PID" ] 
+    then
+      stop
 	    start
 	  fi
 	  ;;
   restart|reload|force-reload)
-        stop
-        start
-        RETVAL=$?
-        ;;
+    stop
+    start
+    RETVAL=$?
+    ;;
   *)
-        echo $"Usage: $0 {start|stop|restart|status}"
-
-        exit 1
+  echo $"Usage: $0 {start|stop|restart|status}"
+  exit 1
 esac
+
 exit $RETVAL
